
service: sls-cic
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  memorySize: 128
  timeOut: 3

functions:
  hello:
    handler: handler.logger
    events: 
      - http:
          path: message
          method: get
